---
apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: egress-metrics-server
  namespace: kube-system
spec:
  selector: k8s-app == 'metrics-server'
  types:
    - Egress
  egress:
    - action: Allow
      protocol: TCP
      destination:
        nets:
          - 10.0.0.9/32
        ports:
          - 10250
